### ISSUE TITLE
Http error 405 on cloudflare pages

### ISSUE THREAD

**Issue by showgood163** [lete114/deeplx-serverless#2]
Hi, there. Thank you for this repo.

I forked your repo and deployed a Cloudflare page based on this repo.
When I tested that with curl, it returns http error 405.

Is that normal? If not, how to fix this problem? I don't know where to start.
Below is the curl log.

```
curl -v 'https://xxx.yyy/translate' \
\`> --header 'Content-Type: application/json' \
\`> --header 'Authorization: Bearer deeplx-serverless' \
\`> --data '{
\`quote>     "text": "Hello, World",
\`quote>     "from": "en",
\`quote>     "to": "zh"
\`quote> }'
* Host xxx.yyy:443 was resolved.
* IPv6: 2606:4700:310c::ac42:2c6a, 2606:4700:310c::ac42:2f96
* IPv4: 172.66.44.106, 172.66.47.150
*   Trying [2606:4700:310c::ac42:2c6a]:443...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519MLKEM768 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=xxx.yyy
*  start date: Jul 13 15:36:40 2025 GMT
*  expire date: Oct 11 16:34:45 2025 GMT
*  subjectAltName: host "xxx.yyy" matched cert's "xxx.yyy"
*  issuer: C=US; O=Google Trust Services; CN=WE1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 2: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using ecdsa-with-SHA384
* Connected to xxx.yyy (2606:4700:310c::ac42:2c6a) port 443
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://xxx.yyy/translate
* [HTTP/2] [1] [:method: POST]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: xxx.yyy]
* [HTTP/2] [1] [:path: /translate]
* [HTTP/2] [1] [user-agent: curl/8.14.1]
* [HTTP/2] [1] [accept: */*]
* [HTTP/2] [1] [content-type: application/json]
* [HTTP/2] [1] [authorization: Bearer deeplx-serverless]
* [HTTP/2] [1] [content-length: 64]
> POST /translate HTTP/2
> Host: xxx.yyy
> User-Agent: curl/8.14.1
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer deeplx-serverless
> Content-Length: 64
>
* upload completely sent off: 64 bytes
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 405
< date: Sun, 13 Jul 2025 18:00:10 GMT
< content-length: 0
< cf-ray: 95eaada6f8257be5-LAX
< access-control-allow-origin: *
< referrer-policy: strict-origin-when-cross-origin
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=zzz"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< alt-svc: h3=":443"; ma=86400
< server-timing: cfL4;desc="?proto=TCP&rtt=193139&min_rtt=192881&rtt_var=40819&sent=7&recv=9&lost=0&retrans=0&sent_bytes=4557&recv_bytes=1919&delivery_rate=20924&cwnd=252&unsent_bytes=0&cid=d7567117380270c4&ts=281&x=0"
<
* Connection #0 to host xxx.yyy left intact
```

**Comment by lete114** [comment]
cloudflare pages?
I don't know much about pages.

**Comment by lete114** [comment]
Do cloudflare pages support post requests?

**Comment by lete114** [comment]
Maybe you wrote the wrong curl? \`> and \`quote>

**Comment by showgood163** [comment]
> cloudflare pages? I don't know much about pages.

I tried to deploy cloudflare workers by clicking the button on [readme](https://github.com/lete114/deeplx-serverless/blob/main/README.md), but the deployment failed.

Below is the log:

```
Initializing build environment...
Initializing build environment...
Success: Finished initializing build environment
Cloning seed repository...
Cloning from: https://github.com/lete114/deeplx-serverless.git
Overwriting files
Pushing to destination: https://github.com/xxx/yyy.git
Detected the following tools from environment: bun@1.2.15, nodejs@22.16.0
Installing project dependencies: bun install
bun install v1.2.15 (df017990)
Resolving dependencies
error: no commit matching "v0.0.2&path:packages/core" found for "core" (but repository exists)
Failed: error occurred while installing tools or dependencies
```

After that I tried to deploy cloudflare pages and it works.

**Comment by showgood163** [comment]
> Do cloudflare pages support post requests?

Maybe, there are reports stating that POST is not supported.

https://community.cloudflare.com/t/error-405-on-post-method-using-ssl-and-pages-hosting/277695/4

https://community.cloudflare.com/t/cloudflare-pages-bug-post-results-in-405-because-its-trying-to-serve-static/688502

https://community.cloudflare.com/t/405-method-not-allowed-on-cloudflare-pages/338944/5

I tried both `curl -X POST` and `curl -X GET`. Both of them reported http error 405.

**Comment by showgood163** [comment]
> Maybe you wrote the wrong curl? `> and `quote>

I also tried to connect the deployed cloudflare page with [kissTranslator](https://github.com/fishjar/kiss-translator), an open-source chrome translation extension, it reported error 405, too.

**Comment by lete114** [comment]
> error: no commit matching "v0.0.2&path:packages/core" found for "core" (but repository exists)
> Failed: error occurred while installing tools or dependencies

Yeah, I had the same problem.

**Comment by lete114** [comment]
> Installing project dependencies: bun install

This may be an issue triggered by cloudflare installing dependencies using `bun`, as my installation using nodejs is working fine. I'm looking for ways to verify or fix `bun install`

**Comment by lete114** [comment]
I was wondering if there is any way to customize npm install or pnpm install. this works fine on vercel or netlify platforms only cloudflare platform fails!

**Comment by showgood163** [comment]
> I was wondering if there is any way to customize npm install or pnpm install. this works fine on vercel or netlify platforms only cloudflare platform fails!

I searched with keyword "bun install cloudflare workers" and find [this](https://www.answeroverflow.com/m/1333203439261454356).
I didn't do any JavaScript or TypeScript development so you have to check it yourself.

**Comment by lete114** [comment]
The deploy button in the readme should now be working :)

**Comment by showgood163** [comment]
> The deploy button in the readme should now be working :)

Yeah, the deploy is working.

However, when I use KissTranslator, I got http error 500.

When I did curl, I got cf error 1101, which is kind of strange. I did the deployment again and error 1101 still appears.
Note that ip addresses assigned to cloudflare workers are censored by GFW, which is different from cloudflare pages. Thus, I used proxychains to connect.
Below is the log:

```
 proxychains curl -v 'https://xxx.yyy/translate' \
\`> --header 'Content-Type: application/json' \
\`> --header 'Authorization: Bearer deeplx-serverless' \
\`> --data '{
\`quote>     "text": "Hello, World",
\`quote>     "from": "en",
\`quote>     "to": "zh"
\`quote> }'
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.17
* Host xxx.yyy:443 was resolved.
* IPv6: (none)
* IPv4: 224.0.0.1
*   Trying 224.0.0.1:443...
[proxychains] Strict chain  ...  192.168.1.122:1984  ...  xxx.yyy:443  ...  OK
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519MLKEM768 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=xxx.yyy
*  start date: Jul  1 21:55:37 2025 GMT
*  expire date: Sep 29 22:53:49 2025 GMT
*  subjectAltName: host "xxx.yyy" matched cert's "*.xxx.yyy"
*  issuer: C=US; O=Google Trust Services; CN=WE1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 2: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using ecdsa-with-SHA384
* Connected to xxx.yyy (224.0.0.1) port 443
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://xxx.yyy/translate
* [HTTP/2] [1] [:method: POST]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: xxx.yyy]
* [HTTP/2] [1] [:path: /translate]
* [HTTP/2] [1] [user-agent: curl/8.14.1]
* [HTTP/2] [1] [accept: */*]
* [HTTP/2] [1] [content-type: application/json]
* [HTTP/2] [1] [authorization: Bearer deeplx-serverless]
* [HTTP/2] [1] [content-length: 64]
> POST /translate HTTP/2
> Host: xxx.yyy
> User-Agent: curl/8.14.1
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer deeplx-serverless
> Content-Length: 64
>
* upload completely sent off: 64 bytes
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 500
< date: Mon, 14 Jul 2025 10:11:18 GMT
< content-type: text/html; charset=UTF-8
< content-length: 4372
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=zzz"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< x-frame-options: SAMEORIGIN
< referrer-policy: same-origin
< cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< expires: Thu, 01 Jan 1970 00:00:01 GMT
< server: cloudflare
< cf-ray: 95f03c36b9c15027-LAX
< alt-svc: h3=":443"; ma=86400
< server-timing: cfL4;desc="?proto=TCP&rtt=202253&min_rtt=194387&rtt_var=56097&sent=7&recv=9&lost=0&retrans=0&sent_bytes=4528&recv_bytes=2431&delivery_rate=20712&cwnd=247&unsent_bytes=0&cid=ba88b2f4a2f1b7c1&ts=866&x=0"
<
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Worker threw exception | xxx.yyy | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" /><![endif]-->
<style>body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!-->
<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>
<!--<![endif]-->


</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1101</span>
          <small class="heading-ray-id">Ray ID: 95f03c36b9c15027 &bull; 2025-07-14 10:11:18 UTC</small>
        </h1>
        <h2 class="cf-subheadline" data-translate="error_desc">Worker threw exception</h2>
      </div><!-- /.header -->

      <section></section><!-- spacer -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>You've requested a page on a website (xxx.yyy) that is on the <a href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a> network. An unknown error occurred while rendering the page.</p>
          </div>


          <div class="cf-column">
            <h2 data-translate="what_can_i_do">What can I do?</h2>
            <p><strong>If you are the owner of this website:</strong><br />refer to <a href="https://developers.cloudflare.com/workers/observability/errors/" target="_blank">Workers - Errors and Exceptions</a> and check Workers Logs for xxx.yyy.</p>
          </div>

        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">95f03c36b9c15027</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">abcde</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script>
  window._cf_translation = {};


</script>

</body>
</html>
* Connection #0 to host xxx.yyy left intact
```

**Comment by lete114** [comment]
Take a look at the Workers log.

**Comment by showgood163** [comment]
> Take a look at the Workers log.

Well, http error 500 from the translation extension means too many requests, while curl never reaches the worker.

```
POST https://xxx.yyy/translate

"exception": {
  "stack": "    at translate (index.js:98:11)\n    at async handle (index.js:248:24)\n    at async index (index.js:217:16)",
  "name": "Error",
  "message": "Too many requests, your IP has been blocked by DeepL temporarily, please don't request it frequently in a short time.",
  "timestamp": 1752488871867
}
```

**Comment by lete114** [comment]
This is probably due to the fact that I didn't add an exception to `translate (index.js:98:11)` which triggered workers to report error 1101

**Comment by showgood163** [comment]
No luck. I just did a fresh deployment with the latest commit. cf error 1101 and http error 500 still occurs.

**Comment by lete114** [comment]
I tested it and it works fine using the deploy button in the readme

**Comment by wuxia101** [comment]
> No luck. I just did a fresh deployment with the latest commit. cf error 1101 and http error 500 still occurs.

Some Error

Error: Too many requests, your IP has been blocked by DeepL temporarily, please don't request it frequently in a short time.
    at translate (file:///var/task/node_modules/deeplx-lib/dist/index.mjs:11:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async handle (file:///var/task/node_modules/deeplx-serverless/packages/core/dist/index.mjs:80:24)
    at async index (file:///var/task/node_modules/deeplx-serverless/packages/core/dist/index.mjs:49:16)
    at async default (/vercel/path0/api/index.ts:8:23)
    at async r (/opt/rust/nodejs.js:2:16523)
    at async Server.<anonymous> (/opt/rust/nodejs.js:2:12474)
    at async Server.<anonymous> (/opt/rust/nodejs.js:17:14562)

**Comment by lete114** [comment]
> > No luck. I just did a fresh deployment with the latest commit. cf error 1101 and http error 500 still occurs.
> 
> Some Error
> 
> Error: Too many requests, your IP has been blocked by DeepL temporarily, please don't request it frequently in a short time. at translate (file:///var/task/node_modules/deeplx-lib/dist/index.mjs:11:11) at process.processTicksAndRejections (node:internal/process/task_queues:104:5) at async handle (file:///var/task/node_modules/deeplx-serverless/packages/core/dist/index.mjs:80:24) at async index (file:///var/task/node_modules/deeplx-serverless/packages/core/dist/index.mjs:49:16) at async default (/vercel/path0/api/index.ts:8:23) at async r (/opt/rust/nodejs.js:2:16523) at async Server. (/opt/rust/nodejs.js:2:12474) at async Server. (/opt/rust/nodejs.js:17:14562)

This is normal; the IP address of the server making the request has been blocked.
